############################
## CHANGE THESE
############################

baseURL: "https://Joerdis0312.github.io/blog"
title: blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
highlight:
    style: dracula
    noClasses: false
params:
  custom_css: ["css/custom.css"]